/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct bakery_t {
	int number;
	int idx;
	int pid;
	int result;
};
typedef struct bakery_t bakery_t;

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_number 1
extern  struct bakery_t * get_number_1(struct bakery_t *, CLIENT *);
extern  struct bakery_t * get_number_1_svc(struct bakery_t *, struct svc_req *);
#define wait_queue 2
extern  struct bakery_t * wait_queue_1(struct bakery_t *, CLIENT *);
extern  struct bakery_t * wait_queue_1_svc(struct bakery_t *, struct svc_req *);
#define bakery_res 3
extern  struct bakery_t * bakery_res_1(struct bakery_t *, CLIENT *);
extern  struct bakery_t * bakery_res_1_svc(struct bakery_t *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_number 1
extern  struct bakery_t * get_number_1();
extern  struct bakery_t * get_number_1_svc();
#define wait_queue 2
extern  struct bakery_t * wait_queue_1();
extern  struct bakery_t * wait_queue_1_svc();
#define bakery_res 3
extern  struct bakery_t * bakery_res_1();
extern  struct bakery_t * bakery_res_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bakery_t (XDR *, bakery_t*);

#else /* K&R C */
extern bool_t xdr_bakery_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
