/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <time.h>

void bakery_prog_2(char *host)
{
    CLIENT *clnt;
    struct bakery_t *result_1;
    struct bakery_t get_number_1_arg;
    struct bakery_t *result_2;
    struct bakery_t get_result_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    srand(time(NULL));
    sleep(rand() % 5 + 1);

    result_1 = get_number_2(&get_number_1_arg, clnt);
    if (result_1 == (struct bakery_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }

    struct timeval current_time;

    time_t raw_time;
    struct tm *timeinfo;
    char time_buf[80];

    time(&raw_time);
    timeinfo = localtime(&raw_time);
    gettimeofday(&current_time, NULL);
    strftime(time_buf, 80, "%H:%M:%S", timeinfo);

    printf("Клиент (pid = %d) получил номер %d, time = %s:%ld\n", getpid(), result_1->number, time_buf, current_time.tv_usec);

    srand(time(NULL));
    sleep(rand() % 7 + 1);

    get_result_1_arg.number = result_1->number;

    result_2 = get_result_2(&get_result_1_arg, clnt);
    if (result_2 == (struct bakery_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }

    time(&raw_time);
    timeinfo = localtime(&raw_time);
    gettimeofday(&current_time, NULL);
    strftime(time_buf, 80, "%H:%M:%S", timeinfo);

    printf("Клиент (pid = %d) получил ответ %c, time = %s:%ld\n", getpid(), result_2->result, time_buf, current_time.tv_usec);

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
    char *host;

    if (argc < 2)
    {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    bakery_prog_2(host);
    exit(0);
}
