/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct bakery_t *
get_number_2(struct bakery_t *argp, CLIENT *clnt)
{
	static struct bakery_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_number,
		(xdrproc_t) xdr_bakery_t, (caddr_t) argp,
		(xdrproc_t) xdr_bakery_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct bakery_t *
get_result_2(struct bakery_t *argp, CLIENT *clnt)
{
	static struct bakery_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_result,
		(xdrproc_t) xdr_bakery_t, (caddr_t) argp,
		(xdrproc_t) xdr_bakery_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
