/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <time.h>
#include <unistd.h> // sleep

void bakery_prog_2(char *host)
{
    CLIENT *clnt;
    struct bakery_t *result_1;
    struct bakery_t get_number_2_arg;
    struct bakery_t *result_2;
    struct bakery_t bakery_service_2_arg;

#ifndef DEBUG
    clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    time_t start_numb, end_numb, start_wait, end_wait, start_serv, end_serv;

    srand(time(NULL));
    double sleep_time = (double)rand() / RAND_MAX * 1000000 * 1.5;
    usleep(sleep_time);

    start_numb = clock();

    // получил номер клиента на обслуживание
    result_1 = get_number_2(&get_number_2_arg, clnt);

    if (result_1 == (struct bakery_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }

    end_numb = clock();

    sleep(rand() % 5 + 1);

    bakery_service_2_arg.number = result_1->number;

    start_wait = clock();
    // обслуживание клиента
    result_2 = bakery_service_2(&bakery_service_2_arg, clnt);

    if (result_2 == (struct bakery_t *)NULL)
    {
        clnt_perror(clnt, "call failed");
    }

    end_wait = clock();

    printf("Клиент (pid = %d) получил %c за время %lf \n", getpid(), result_2->result, (difftime(end_numb, start_numb) + difftime(end_wait, start_wait)));

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
    char *host;

    if (argc < 2)
    {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    bakery_prog_2(host);
    exit(0);
}
