/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct bakery_t {
	int number;
	int result;
};
typedef struct bakery_t bakery_t;

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 2

#if defined(__STDC__) || defined(__cplusplus)
#define get_number 1
extern  struct bakery_t * get_number_2(struct bakery_t *, CLIENT *);
extern  struct bakery_t * get_number_2_svc(struct bakery_t *, struct svc_req *);
#define bakery_service 2
extern  struct bakery_t * bakery_service_2(struct bakery_t *, CLIENT *);
extern  struct bakery_t * bakery_service_2_svc(struct bakery_t *, struct svc_req *);
extern int bakery_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_number 1
extern  struct bakery_t * get_number_2();
extern  struct bakery_t * get_number_2_svc();
#define bakery_service 2
extern  struct bakery_t * bakery_service_2();
extern  struct bakery_t * bakery_service_2_svc();
extern int bakery_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bakery_t (XDR *, bakery_t*);

#else /* K&R C */
extern bool_t xdr_bakery_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
