/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_bakery_t (XDR *xdrs, bakery_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
